// Design color palette — bolder fitness aesthetic

const palette = {
  // Light theme
  lightText: '#0F172A',
  lightSecondaryText: '#64748B',
  lightBackground: '#F1F5F9',
  lightIcon: '#94A3B8',
  lightTint: '#0F172A',

  lightPrimary: '#6366F1',
  lightPrimaryLight: '#818CF8',
  lightPrimaryGlow: 'rgba(99, 102, 241, 0.25)',
  lightAccent: '#10B981',
  lightWarning: '#F59E0B',
  lightError: '#EF4444',
  lightOnPrimary: '#FFFFFF',
  lightGoogleBlue: '#EEF2FF',
  lightInputBackground: '#FFFFFF',
  lightBorder: '#CBD5E1',
  lightBorderLight: '#E2E8F0',
  lightPlaceholder: '#94A3B8',
  lightCardBackground: '#FFFFFF',
  lightShadow: '#0F172A',

  // Dark theme
  darkText: '#F8FAFC',
  darkSecondaryText: '#B4C0CE',
  darkBackground: '#0A0A0F',
  darkIcon: '#94A3B8',
  darkTint: '#F8FAFC',

  darkPrimary: '#818CF8',
  darkPrimaryLight: '#A5B4FC',
  darkPrimaryGlow: 'rgba(129, 140, 248, 0.3)',
  darkAccent: '#34D399',
  darkWarning: '#FBBF24',
  darkError: '#F87171',
  darkOnPrimary: '#0F0F1A',
  darkGoogleBlue: '#60A5FA',
  darkInputBackground: '#12121A',
  darkBorder: '#2D2D3A',
  darkBorderLight: '#1E1E2A',
  darkPlaceholder: '#64748B',
  darkCardBackground: '#12121A',
  darkShadow: '#000000',
};

export const Colors = {
  light: {
    text: palette.lightText,
    secondaryText: palette.lightSecondaryText,
    background: palette.lightBackground,
    tint: palette.lightTint,
    icon: palette.lightIcon,
    tabIconDefault: palette.lightIcon,
    tabIconSelected: palette.lightTint,
    primary: palette.lightPrimary,
    primaryLight: palette.lightPrimaryLight,
    primaryGlow: palette.lightPrimaryGlow,
    accent: palette.lightAccent,
    warning: palette.lightWarning,
    error: palette.lightError,
    onPrimary: palette.lightOnPrimary,
    googleBlue: palette.lightGoogleBlue,
    inputBackground: palette.lightInputBackground,
    border: palette.lightBorder,
    borderLight: palette.lightBorderLight,
    placeholder: palette.lightPlaceholder,
    cardBackground: palette.lightCardBackground,
    shadow: palette.lightShadow,
  },
  dark: {
    text: palette.darkText,
    secondaryText: palette.darkSecondaryText,
    background: palette.darkBackground,
    tint: palette.darkTint,
    icon: palette.darkIcon,
    tabIconDefault: palette.darkIcon,
    tabIconSelected: palette.darkTint,
    primary: palette.darkPrimary,
    primaryLight: palette.darkPrimaryLight,
    primaryGlow: palette.darkPrimaryGlow,
    accent: palette.darkAccent,
    warning: palette.darkWarning,
    error: palette.darkError,
    onPrimary: palette.darkOnPrimary,
    googleBlue: palette.darkGoogleBlue,
    inputBackground: palette.darkInputBackground,
    border: palette.darkBorder,
    borderLight: palette.darkBorderLight,
    placeholder: palette.darkPlaceholder,
    cardBackground: palette.darkCardBackground,
    shadow: palette.darkShadow,
  },
};

export default Colors;
